import SideBar from '@/components/SideBar'
import StatusBar from '@/components/StatusBar'
import { ClerkProvider } from '@clerk/nextjs'
import localFont from 'next/font/local'
import './globals.css'

// const firaCode = Fira_Code({
//   subsets: ['latin'],
//   fallback: ['monospace'],
// })

const localFiraCode = localFont({
  src: '../public/font/FiraCode-VariableFont_wght.ttf',
})

export const metadata = {
  title: 'DVSTASH | Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${localFiraCode.className} flex`}>
          {/* SideBar */}
          <SideBar />

          <div className="flex h-screen flex-1 flex-col">
            <div className="flex-1">{children}</div>
            <StatusBar />
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
