import SideBar from '@/components/SideBar'
import { Fira_Code } from 'next/font/google'
import './globals.css'

const firaCode = Fira_Code({ subsets: ['latin'] })

export const metadata = {
  title: 'DVSTASH | Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} flex`}>
        {/* SideBar */}
        <SideBar />

        <main className="flex-1 h-screen bg-od_black">{children}</main>
      </body>
    </html>
  )
}
